[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name="bazaar"
version="0.0.1-dev"
dependencies=[
    "fastapi[all]",
    "proxmoxer",
    "requests"
]